### ISSUE TITLE
Live demo links in README don't work

### ISSUE THREAD

**Issue by dbackeus** [joakimk/orbital-game#1]
Running the index.html files locally after downloading won't work since images are not available.

Fun project in any case and hope you get time to stabilize the simulation.

**Comment by joakimk** [comment]
Ah, thanks for telling me. I've moved the examples to github and used rawgit.com to serve them. The links should work again.

We'll see if I continue working on this simulation or something based on it. I still want to make a little 2d spaceship game someday :)
